feat: add microservice code (#1)
* feat: add microservice code

* Update ReadMe

diff --git a/test/advance.cloudbuild.yaml b/test/advance.cloudbuild.yaml
--- a/test/advance.cloudbuild.yaml
+++ b/test/advance.cloudbuild.yaml
@@ -10,11 +10,86 @@
 # limitations under the License.
 
 steps:
+- id: 'Install Testing Dependencies'
+  name: node:14-slim
+  args: ['npm', 'install']
 
-- id: 'Break FlakyBot Test'
+- id: 'Lint'
+  name: node:14-slim
+  args: ['npm', 'run', 'lint']
+
+- id: 'Run Unit Tests'
+  name: node:14-slim
+  args: ['npm', 'run', 'test']
+
+# Setup resources for system tests
+
+- id: 'Build Container Image'
+  name: 'gcr.io/k8s-skaffold/pack'
+  entrypoint: pack
+  args:
+    - build
+    - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA' # Tag docker image with git commit SHA
+    - '--builder=gcr.io/buildpacks/builder:v1'
+    - '--path=.'
+    
+
+- id: 'Push Container Image'
+  name: 'gcr.io/cloud-builders/docker:latest'
+  args:
+    - push
+    - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA' 
+
+- id: 'Deploy to Cloud Run'
   name: 'gcr.io/cloud-builders/gcloud:latest'
   entrypoint: /bin/bash
   args:
     - '-c'
     - |
-      exit 1
+      cat /dev/urandom | LC_CTYPE=C tr -dc 'a-z0-9' | head -c 15 > _short_id # Generate a random 15 character alphanumeric string (lowercase only)
+      gcloud run deploy ${_SERVICE_NAME}-$(cat _short_id) \
+        --image $_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA \
+        --region ${_DEPLOY_REGION} \
+        --platform ${_PLATFORM} \
+        --no-allow-unauthenticated
+
+- id: 'Retrieve Service URL'
+  name: 'gcr.io/cloud-builders/gcloud:latest'
+  entrypoint: /bin/bash
+  args:
+    - '-c'
+    - |
+      set -e
+      source /workspace/test/common.sh
+      echo $(get_url) > _service_url
+      echo $(get_idtoken) > _id_token
+  env:
+    - '_SERVICE_NAME=${_SERVICE_NAME}'
+    - '_DEPLOY_REGION=${_DEPLOY_REGION}'
+    - 'PROJECT_ID=${PROJECT_ID}'
+  
+- id: 'Run System Tests'
+  name: node:14-slim
+  entrypoint: /bin/bash
+  args:
+    - '-c'
+    - |
+      export BASE_URL=$(cat _service_url)
+      export ID_TOKEN=$(cat _id_token)
+      npm run system-test
+
+# Clean up system test resources
+- id: 'Delete image and service'
+  name: 'gcr.io/cloud-builders/gcloud'
+  entrypoint: '/bin/bash'
+  args:
+    - '-c'
+    - |
+      gcloud container images delete $_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA --quiet
+      gcloud run services delete ${_SERVICE_NAME}-$(cat _short_id) --region ${_DEPLOY_REGION} --platform ${_PLATFORM} --quiet
+
+substitutions:
+  _GCR_HOSTNAME: us.gcr.io
+  _SERVICE_NAME: microservice-template
+  _DEPLOY_REGION: us-central1
+  _PLATFORM: managed
